[build]
  command = "pip install -r requirements.txt"
  publish = "build"

[build.environment]
  CPLUS_INCLUDE_PATH = "/usr/include/dlib/:"
  LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/"
  LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu/"

[functions]
  external_node_modules = ["dlib"]

[build.lifecycle]
  post_install = "pip install cmake"